openapi: 3.1.0
info:
  description: Ping
  title: Ping
  version: 1.0.0
servers:
- url: /
paths:
  /ping:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                example: Pong
                type: string
          description: Afficher Pong
      summary: Retourne Pong
      x-accepts:
      - text/plain
components:
  schemas: {}

