openapi: 3.1.0
info:
  title: Ping
  description: Ping
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Retourne Pong
      responses:
        "200":
          description: Afficher Pong
          content:
            text/plain:
              schema:
                type: string
                example: "Pong"
