spring.application.name=ingredient-again
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ingredient-again
spring.datasource.username=doudou
spring.datasource.password=1622Val++
