spring.application.name=ingredient-again
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ingredient-again
spring.datasource.username=doudou
spring.datasource.password=1622Val++

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect